# Generated by Django 6.0.5 on 2026-05-12 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adspend',
            name='raw_spend_month',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='adspend',
            name='raw_spend_week',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='adspend',
            name='week_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='adspend',
            name='week_start',
            field=models.DateField(),
        ),
    ]
